name: Integration Tests for PR

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Syndesis
        run: tools/bin/syndesis build --backend --flash --clean
      - name: Build Docker images
        run: tools/bin/syndesis build -m s2i -i -f --docker
      - name: Show available Docker images
        run: docker image list
      - name: Run integration tests
        run: tools/bin/syndesis integration-test


